#
# (c) 2012 Commonwealth of Australia
#     Australian Bureau of Meteorology, COSPPac COMP
#     All Rights Reserved
#
# Authors: Sheng Guo <s.guo@bom.gov.au>

regions = {
    'cook': ('pac',
           {'llcrnrlat': -23,
            'llcrnrlon': 193,
            'urcrnrlat': -8,
            'urcrnrlon': 203
           },
           "Cook Islands",
           {}),
    'cook_nor': ('pac',
           {'llcrnrlat': -15.583,
            'llcrnrlon': 191.476,
            'urcrnrlat': -5.853,
            'urcrnrlon': 205.073
           },
           "Northern Group",
           {'parent': 'cook'}),
    'cook_sou': ('pac',
           {'llcrnrlat': -25.277,
            'llcrnrlon': 193.357,
            'urcrnrlat': -15.583,
            'urcrnrlon': 205.194
           },
           "Southern Group",
           {'parent': 'cook'}),
    'fsm': ('pac',
           {'llcrnrlat': 5,
            'llcrnrlon': 135.275,
            'urcrnrlat': 11,
            'urcrnrlon': 164
           },
           "Federated States of Micronesia",
           {}),
    'fsm_east': ('pac',
           {'llcrnrlat': -1.18,
            'llcrnrlon': 141,
            'urcrnrlat': 12.322,
            'urcrnrlon': 165.675
           },
           "Eastern FSM",
           {'parent': 'fsm'}),
    'fsm_west': ('pac',
           {'llcrnrlat': 3.35,
            'llcrnrlon': 135.275,
            'urcrnrlat': 13.422,
            'urcrnrlon': 143
           },
           "Western FSM",
           {'parent': 'fsm'}),
    'fiji': ('pac',
           {'llcrnrlat': -20,
            'llcrnrlon': 176.5,
            'urcrnrlat': -15,
            'urcrnrlon': 183
           },
           "Fiji",
           {}),
    'kiribati': ('pac',
           {'llcrnrlat': -12,
            'llcrnrlon': 169,
            'urcrnrlat': 5,
            'urcrnrlon': 210
           },
           "Kiribati",
           {'resolution': 'h'}),
    'kiribati_gilbert': ('pac',
           {'llcrnrlat': -4.357,
            'llcrnrlon': 167.815,
            'urcrnrlat': 5.569,
            'urcrnrlon': 180.18
           },
           "Gilbert Islands",
           {'parent': 'kiribati'}),
    'kiribati_phoenix': ('pac',
           {'llcrnrlat': -7.773,
            'llcrnrlon': 182.11,
            'urcrnrlat': 0.563,
            'urcrnrlon': 192.63
           },
           "Phoenix Islands",
           {'parent': 'kiribati'}),
    'kiribati_nor_line': ('pac',
           {'llcrnrlat': -2,
            'llcrnrlon': 196.913,
            'urcrnrlat': 7.918,
            'urcrnrlon': 208.444
           },
           "Northern Line Islands",
           {'parent': 'kiribati'}),
    'kiribati_sou_line': ('pac',
           {'llcrnrlat': -13.84,
            'llcrnrlon': 200.718,
            'urcrnrlat': -1,
            'urcrnrlon': 213.179
           },
           "Southern Line Islands",
           {'parent': 'kiribati'}),
    'marshall': ('pac',
           {'llcrnrlat': 4,
            'llcrnrlon': 160,
            'urcrnrlat': 16,
            'urcrnrlon': 173
           },
           "Marshall Islands",
           {'resolution': 'f'}),
    'nauru': ('pac',
           {'llcrnrlat': -1,
            'llcrnrlon': 166,
            'urcrnrlat': 0,
            'urcrnrlon': 168
           },
           "Nauru",
           {}),
    'niue': ('pac',
           {'llcrnrlat': -20,
            'llcrnrlon': 189,
            'urcrnrlat': -18,
            'urcrnrlon': 191
           },
           "Niue",
           {}),
    'palau': ('pac',
           {'llcrnrlat': 2,
            'llcrnrlon': 131,
            'urcrnrlat': 9,
            'urcrnrlon': 135
           },
           "Palau",
           {}),
    'png': ('pac',
           {'llcrnrlat': -12,
            'llcrnrlon': 128,
            'urcrnrlat': 1,
            'urcrnrlon': 160
           },
           "Papua New Guinea",
           {}),
    'samoa': ('pac',
           {'llcrnrlat': -15,
            'llcrnrlon': 186.5,
            'urcrnrlat': -12,
            'urcrnrlon': 189
           },
           "Samoa",
           {}),
    'wsm_nor': ('pac',
           {'llcrnrlat': -14,
            'llcrnrlon': 186.5,
            'urcrnrlat': -12,
            'urcrnrlon': 189
           },
           "Samoa Northern Coast",
           {'parent': 'samoa'}),
    'wsm_sou': ('pac',
           {'llcrnrlat': -15,
            'llcrnrlon': 186.5,
            'urcrnrlat': -13.3,
            'urcrnrlon': 189
           },
           "Samoa Southern Coast",
           {'parent': 'samoa'}),
    'solomon': ('pac',
           {'llcrnrlat': -12,
            'llcrnrlon': 155,
            'urcrnrlat': -4.8,
            'urcrnrlon': 168
           },
           "Solomon Islands",
           {}),
    'tonga': ('pac',
           {'llcrnrlat': -22,
            'llcrnrlon': 184,
            'urcrnrlat': -15,
            'urcrnrlon': 190
           },
           "Tonga",
           {}),
    'tuvalu': ('pac',
           {'llcrnrlat': -11,
            'llcrnrlon': 177,
            'urcrnrlat': -4,
            'urcrnrlon': 180
           },
           "Tuvalu",
           {}),
    'vanuatu': ('pac',
           {'llcrnrlat': -21,
            'llcrnrlon': 166,
            'urcrnrlat': -13,
            'urcrnrlon': 170
           },
           "Vanuatu",
           {}),
    'vanuatu_northern': ('pac',
           {'llcrnrlat': -16.1,
            'llcrnrlon': 166.0,
            'urcrnrlat': -13.0,
            'urcrnrlon': 170.0},
           "Vanuatu Northern Waters",
           {'parent': 'vanuatu'}),
    'vanuatu_central': ('pac',
           {'llcrnrlat': -18.0,
            'llcrnrlon': 166.0,
            'urcrnrlat': -15.8,
            'urcrnrlon': 170.0},
           "Vanuatu Central Waters",
           {'parent': 'vanuatu'}),
    'vanuatu_southern': ('pac',
           {'llcrnrlat': -20.5,
            'llcrnrlon': 166.0,
            'urcrnrlat': -18.5,
            'urcrnrlon': 170.0},
           "Vanuatu Southern Waters",
           {'parent': 'vanuatu'}),
    'aus': ('aus',
           {'llcrnrlat': -50,
            'llcrnrlon': 60,
            'urcrnrlat': 20,
            'urcrnrlon': 170
           },
           "Australia",
           {}),
    'pac': (None,
           {'llcrnrlat': -45,
            'llcrnrlon': 100,
            'urcrnrlat': 45,
            'urcrnrlon': 300
           },
           "Pacific Ocean",
           {}),
    'ind': ('aus',
           {'llcrnrlat': -45,
            'llcrnrlon': 20,
            'urcrnrlat': 45,
            'urcrnrlon': 160
           },
           "Indian Ocean",
           {}),
    'ntr': ('aus',
           {'llcrnrlat': -22,
            'llcrnrlon': 94,
            'urcrnrlat': 0,
            'urcrnrlon': 174
           },
           "Northern Tropics",
           {}),
    'sth': ('aus',
           {'llcrnrlat': -50,
            'llcrnrlon': 94,
            'urcrnrlat': -30,
            'urcrnrlon': 174
           },
           "Southern Region",
           {}),
    'tas': ('aus',
           {'llcrnrlat': -46,
            'llcrnrlon': 150,
            'urcrnrlat': -26,
            'urcrnrlon': 174
           },
           "Tasman Sea",
           {}),
    'cor': ('aus',
           {'llcrnrlat': -26,
            'llcrnrlon': 142,
            'urcrnrlat': -4,
            'urcrnrlon': 174
           },
           "Coral Sea",
           {}),
    'nws': ('aus',
           {'llcrnrlat': -22,
            'llcrnrlon': 94,
            'urcrnrlat': -4,
            'urcrnrlon': 130
           },
           "North West Shelf",
           {}),
    'swr': ('aus',
           {'llcrnrlat': -46,
            'llcrnrlon': 94,
            'urcrnrlat': -22,
            'urcrnrlon': 116
           },
           "South West Region",
           {}),
    'eca': ('aus',
           {'llcrnrlat': -50,
            'llcrnrlon': 140,
            'urcrnrlat': 0,
            'urcrnrlon': 180
           },
           "East Australian Coast",
           {}),
    'wca': ('aus',
           {'llcrnrlat': -50,
            'llcrnrlon': 90,
            'urcrnrlat': 0,
            'urcrnrlon': 130
           },
           "West Australian Coast",
           {}),
    'qld': ('aus',
           {'llcrnrlat': -29.0,
            'llcrnrlon': 136,
            'urcrnrlat': -9.0,
            'urcrnrlon': 160
           },
           "Queensland / Coral Sea",
           {}),
    'nsw': ('aus',
           {'llcrnrlat': -39,
            'llcrnrlon': 147,
            'urcrnrlat': -27,
            'urcrnrlon': 160
           },
           "N.S.W. Coast",
           {}),
    'seaus': ('aus',
           {'llcrnrlat': -46,
            'llcrnrlon': 139,
            'urcrnrlat': -37,
            'urcrnrlon': 151
           },
           "Victoria / Tasmania",
           {}),
    'sa': ('aus',
           {'llcrnrlat': -40.3,
            'llcrnrlon': 128.6,
            'urcrnrlat': -30.5,
            'urcrnrlon': 141.5
           },
           "S.A. / Great Australian Bight",
           {}),
    'nt': ('aus',
           {'llcrnrlat': -16.5,
            'llcrnrlon': 127,
            'urcrnrlat': -7.5,
            'urcrnrlon': 140
           },
           "Northern Territory",
           {}),
    'nwa': ('aus',
           {'llcrnrlat': -23,
            'llcrnrlon': 108,
            'urcrnrlat': -10,
            'urcrnrlon': 131
           },
           "North Western Australia",
           {}),
    'swa': ('aus',
           {'llcrnrlat': -39,
            'llcrnrlon': 108,
            'urcrnrlat': -22,
            'urcrnrlon': 131
           },
           "South Western Australia",
           {}),
    'christmas': ('aus',
           {'llcrnrlat': -13.1,
            'llcrnrlon': 102.8,
            'urcrnrlat': -7.8,
            'urcrnrlon': 109
           },
           "Christmas Island",
           {}),
    'cocos': ('aus',
           {'llcrnrlat': -15,
            'llcrnrlon': 93.7,
            'urcrnrlat': -9,
            'urcrnrlon': 99.7
           },
           "Cocos (Keeling) Island",
           {}),
    'lordhowe': ('aus',
           {'llcrnrlat': -34,
            'llcrnrlon': 156,
            'urcrnrlat': -28.5,
            'urcrnrlon': 162
           },
           "Lord Howe Island",
           {}),
    'norfolk': ('aus',
           {'llcrnrlat': -32,
            'llcrnrlon': 165,
            'urcrnrlat': -26,
            'urcrnrlon': 171
           },
           "Norfolk Island",
           {}),
    'macquarie': ('aus',
           {'llcrnrlat': -57,
            'llcrnrlon': 156,
            'urcrnrlat': -52,
            'urcrnrlon': 162
           },
           "Macquarie Island",
           {}),
}
